#! /bin/sh

set -e

lb config noauto \
   --distribution "jessie" \
   --archive-areas "main contrib non-free"  \
   --architecture amd64 \
   --bootappend-live "boot=live config locales=en_US.UTF-8" \
   "${@}"
