#! /bin/sh

lb config noauto \
	--architectures i386 \
	--distribution jessie \
	--linux-flavours "586 686-pae" \
	--debian-installer live \
	--debian-installer-distribution jessie \
	--debian-installer-gui true \
	--system live \
	--archive-areas "main contrib non-free" \
"${@}"
