#! /bin/sh

lb config noauto \
	--architectures amd64 \
	--distribution jessie \
	--linux-flavours "amd64" \
	--debian-installer live \
	--debian-installer-distribution jessie \
	--debian-installer-gui true \
	--system live \
	--archive-areas "main contrib non-free" \
"${@}"
